---
# tasks file for singleEC2

- name: Provision EC2 instance
  ec2:
      key_name: "{{ keyName }}"
      region: "{{ awsRegion }}"
      instance_type: "{{ instanceType }}"
      image: "{{ imageId }}"
      wait: yes
      wait_timeout: 500
      count: "{{ instanceCount }}"
      instance_tags:
        Name: "{{ tagName }}"
        Group: "{{ tagGroup }}"
      vpc_subnet_id: "{{ vpcSubnetId }}"
      assign_public_ip: yes
      group: "{{ securityGroupName }}"
      group_id: "{{ securityGroupId }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
  with_items: "{{ ec2.instances }}"
  
- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ item.public_ip }}"
    groups: webservers
  with_items: "{{ ec2.instances }}"  
