---
# tasks file for ec2
- name: Provision EC2 instance
  ec2:
      key_name: "{{ keyName }}"
      region: "{{ awsRegion }}"
      instance_type: "{{ instanceType }}"
      image: "{{ imageId }}"
      wait: yes
      wait_timeout: 500
      count: "{{ item.value }}"
      instance_tags:
        Name: "{{ tagName }}"
        Group: "{{ tagGroup }}"
      vpc_subnet_id: "{{ item.key }}"
      assign_public_ip: yes
      group: "{{ securityGroupName }}"
      group_id: "{{ securityGroupId }}"
  with_dict: "{{ vpcSubnetIdList }}"    
  register: ec2

- name: Wait for SSH to come up
  wait_for:
      host: "{{ item.1.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
  #with_items: "{{ ec2.instances }}"
  loop: "{{lookup('subelements', ec2.results, 'instances' )}}"
  
- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ item.1.private_ip }}"
    groups: webservers
  #with_items: "{{ ec2.instances }}"  
  loop: "{{lookup('subelements', ec2.results, 'instances' )}}"