- hosts: localhost
  become: true
  roles:
    - ec2 

- name: Execution of route53  
  hosts: localhost
  become: true
  roles:
    - route53
  #tasks:
  
- name: SSH to servers
  hosts: domaingroup
  remote_user: ubuntu
  become: yes
  gather_facts: no
  roles:
    - dependencies
    - zookeeper
