- hosts: localhost
  become: true
  roles:
    - ec2

- name: SSH to servers
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  roles:
    - dependencies
    - kafka
