- hosts: localhost
  become: true
  roles:
    - role: ec2 
      instanceName: zookeeper

- name: Execution of route53  
  hosts: localhost
  become: true
  roles:
    - role: route53
      zone: "streams.com"
      recordPrifix: "zk"
  #tasks:
  
- name: SSH to servers
  hosts: domaingroup
  remote_user: ubuntu
  become: yes
  gather_facts: no
  roles:
    - dependencies
    - zookeeper
